---
exclude: migrations|templates|fixtures
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: /
      - id: end-of-file-fixer
        files: /
      - id: check-ast
        files: /
  - repo: https://github.com/myint/autoflake # removes unused imports
    rev: v2.0.1
    hooks:
      - id: autoflake
        files: /
        args:
          [
            -i,
            --remove-all-unused-imports,
            --ignore-init-module-imports,
            --expand-star-imports,
            --remove-duplicate-keys,
          ]
  - repo: https://github.com/pycqa/isort # sorts imports
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ -sl, --settings-file, ./pyproject.toml, --profile, black ]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        files: /
        language_version: python3
        args: [ --config, ./pyproject.toml ]
        additional_dependencies:
          - "click==8.0.4"
  - repo: https://github.com/radix-ai/auto-smart-commit # prepends jira ticket number to each commit
    rev: v1.0.2
    hooks:
      - id: auto-smart-commit

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]
        args: [check, --fix]
        require_serial: true
        pass_filenames: false
