
services:
  elasticsearch:
    image: elasticsearch:9.0.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # For simplicity, disable security for this template
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hybrid-search-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./models:/app/models
      - ./scripts:/app/scripts
      - ./.env:/app/.env
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}
    command: pdm run uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  es_data:
    driver: local
